name: Update Kurukuru

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Kurukuru
        shell: pwsh
        id: download-kurukuru
        run: ./tools/download_kurukuru.ps1

      - name: Copy DLL
        continue-on-error: true
        run: cp ${{github.workspace}}/tmp/New-Kurukuru.dll lib/Kurukuru.dll

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Kurukuru.dll
          delete-branch: true
          branch: auto/update-kurukuru-${{ steps.download-kurukuru.outputs.kurukuru-version }}
          title: Update Kurukuru.dll ${{ steps.download-kurukuru.outputs.kurukuru-version }}
